### PR TITLE
Feat/better editor

### PR DESCRIPTION
**Pull request by drikusroor**
This PR adds _many_ nice additions:

- Configure React Quill as the body & profile bio editor
- Show body as html with tailwind's [prose](https://tailwindcss.com/docs/plugins#typography) class through the typography plugin
- Add edit button to the post detail page if it's your own post
- Add cancel button to post form, which leads you back to the admin post overview
- Show a nice little preview of the body in the admin posts overview
- Display the avatar in the profile overview and as a preview in the profile form

Related to #78 & #7

### CODE REVIEW

**Comment by naomi-eliasar** [comment]
I think the space between two lines is too big.

The current space between two lines without a white line in between, should be what the current space between two lines with a white line in between is.


Editor:
editor

Article:
Scherm­afbeelding 2023-07-17 om 14 26 55

**Comment by naomi-eliasar** [comment]
The avatar preview is squished, would be nice if it was always round
Scherm­afbeelding 2023-07-17 om 14 32 01

**Comment by naomi-eliasar** [comment]
In the editor it looks like sublists are possible, but they don't show in the published article.
If it's not too difficult, I think it would be nice if sublists are possible & visible in the published article

editor:
Scherm­afbeelding 2023-07-17 om 14 42 08

article:
Scherm­afbeelding 2023-07-17 om 14 41 58

**Comment by naomi-eliasar** [comment]
Do we want to be able to add images in the text as well? if yes, is it possible to add that to the toolbar?
Or would we rather add the possibility to add a picture gallery to an article at the bottom, but no pictures in between the text

**Comment by naomi-eliasar** [comment]
An outline option in the toolbar might be nice too?
Definitely for the Haiku's I can imagine it might be nice if you could outline the text in the center

**Comment by Gakkenyak** [comment]
This only crashes after I made a new post to test the editor.

**Comment by naomi-eliasar** [comment]
The outlining isn't working in the posted article, it is always on the left side

editor:
editor

article:
article

**Comment by naomi-eliasar** [comment]
The different font types also aren't working in the published posts.

But all the other additions to the toolbar are working great!

Editor:
Scherm­afbeelding 2023-07-19 om 13 17 28

Published post:
Scherm­afbeelding 2023-07-19 om 13 17 21

**Comment by drikusroor** [comment]
Closed because we will use solely markdown

**Pull request closed without merging**
