### PR TITLE
Added: Post Location and LocationPin component

### LINKED ISSUE #116: Add location
Make it possible to add a location to an article. This should work for all types of article

### PR DESCRIPTION
**Pull request by drikusroor**
afbeelding

Resolves #116

### CODE REVIEW

**Comment by naomi-eliasar** [comment]
On hover it doesn't show anything for me, but the clicking works

https://github.com/drikusroor/ohayo-goededagu/assets/24891386/d66a56b4-e734-4dbe-95b9-388fe51fa4ba

**Comment by naomi-eliasar** [comment]
If I run it on the test db it works, but if I run it on the prod db it gives an error

Scherm­afbeelding 2023-09-08 om 12 32 07

Terminal:
https://github.com/drikusroor/ohayo-goededagu/assets/24891386/b2e4577e-6150-4f49-ac32-660585a0b868

**Comment by naomi-eliasar** [comment]
The location doesn't show in the preview of the article
Scherm­afbeelding 2023-09-08 om 12 45 44

**Comment by naomi-eliasar** [comment]
If I try to save it gives an error
Scherm­afbeelding 2023-09-08 om 12 46 25

**Comment by drikusroor** [comment]
> The location doesn't show in the preview of the article
> 
> In the deploy preview I cannot test this because I don't have an admin account in there.
> 
> Scherm­afbeelding 2023-09-08 om 12 45 44

afbeelding

But it's here innit? Or what you expecting to see? 😅

**Comment by drikusroor** [comment]
> If I try to save it gives an error Scherm­afbeelding 2023-09-08 om 12 46 25

Could you check the logs?

**Comment by naomi-eliasar** [comment]
> > The location doesn't show in the preview of the article
> > In the deploy preview I cannot test this because I don't have an admin account in there.
> > Scherm­afbeelding 2023-09-08 om 12 45 44
> 
> afbeelding
> 
> But it's here innit? Or what you expecting to see? 😅

I am also expecting it in the big article & blog roll previews
266585449-28eee441-6340-449a-80b0-9cc688cf7c16

**Comment by drikusroor** [comment]
> In the deploy preview I cannot test this because I don't have an admin account in there.

@naomi-eliasar you can check `seed.ts` for the admin accounts (i think)

**Pull request merged**
