### PR TITLE
Feat/delete comment

### LINKED ISSUE #29: Add delete comment feature

### PR DESCRIPTION
**Pull request by drikusroor**
Resolves #29

### CODE REVIEW

**Comment by naomi-eliasar** [comment]
I can also delete comments by other users, I don't think that is the desired behaviour

**Comment by naomi-eliasar** [comment]
I think it would be nicer if the delete button was smaller, and maybe just a trashbin icon
For sure on a mobile screen

**Comment by drikusroor** [comment]
> I can also delete comments by other users, I don't think that is the desired behaviour.
> 
> update: It looks like I can delete comments by others, has the delete button, the confirmation dialog & the animation of the comment being gone. But if I refresh that page, the comment (of the other person) is still there.
> 
> I think we should hide the delete button from comments that aren't yours

Yeah good one. I just added that. I also don't think we really need to think about moderation right? We already moderate by only allowing friends & family to get accounts with rights.

**Comment by naomi-eliasar** [comment]
> 

Yes, I don't think so
If we only allow people we know to comment, I'm sure they won't post any weird stuff
..right? 

What do you think @adrianabm & @Gakkenyak

**Review by naomi-eliasar — APPROVED** [review]

**Pull request merged**
