### PR TITLE
Feat/show article comment count

### PR DESCRIPTION
**Pull request by drikusroor**
Relates to #69

### CODE REVIEW

**Comment by naomi-eliasar** [comment]
In light mode the little comment thing is not visible
Maybe it's possible to give it a border? Or switch color when it's in light mode?
Or make it a light grey color, so it's visible in both light & dark mode

Light mode

**Comment by naomi-eliasar** [comment]
For the Haiku & Chotto article types the styling is not quite right
It is below the avatar, name + timestamp 
I think it will look better if it is on the same line, but on the right side 

Haiku   Chotto

**Comment by naomi-eliasar** [comment]
Can we hide the counter when there are 0 comments?

**Comment by naomi-eliasar** [comment]
When a video has the counter and the 'lees verder' button, I think it will look better if the counter & 'lees verder' button are together in one div on the outer right side, instead how it is now

Video with read more button

**Review by naomi-eliasar — CHANGES_REQUESTED** [review]
The above mentioned styling things for the counter :)

**Comment by drikusroor** [comment]
> The above mentioned styling things for the counter :)

@naomi-eliasar I believe I have resolved your requested changes. Could you check again? ;-)

**Comment by drikusroor** [comment]
@naomi-eliasar going to merge this. You can ping me if you would like more changes and I will address them in a next PR 😉

**Pull request merged**
