### PR TITLE
Feat/67 default cover picture & 68 upload multiple parameter & 70 pro image preview 

### PR DESCRIPTION
**Pull request by naomi-eliasar**
**#67**
I set the logo as a default cover image if no cover image is uploaded for a post of type article 

**#68**
Add the multiple parameter to the upload component, default is set to true

**#70**
I created a pro preview version of the uploaded cover image:
- Has the option to view the cover image on the blog roll (home page)
- Has the option view the cover image on the full article page
- The title & body change when you change the input fields
- The name is from the currentUser
- The date is the currentDate

I think it could be improved by using the users profile for the name & avatar. But I did not figure out how to get that. Any help to get me in the right direction are appreciated

### CODE REVIEW

**Comment by drikusroor** [comment]
As we will now show the logo when no cover image has been uploaded, should we also show this during the preview mode?

**Review by drikusroor — CHANGES_REQUESTED** [review]
Although I do like the additional features, I think it would be better if we show the preview not in the `Upload` component but in a different component.

And also mentioned in another comment: Can we also show the preview when there is not yet a cover image?

**Review by drikusroor — APPROVED** [review]

**Comment by drikusroor** [comment]
> I think it could be improved by using the users profile for the name & avatar. But I did not figure out how to get that. Any help to get me in the right direction are appreciated

If you want to do this, I suggest you to try the following:
- Remove the `getCurrentUser` from the `Preview` component and add a `name` prop. This will make the component "dumber", which in this case is a good thing I think. It is independent of any state and only dependent on the props.

Then, we need to fetch the profile information somehow somewhere. There are several ways to do this:

1. You can do that either by changing the query that returns the current user so that it will also return profile information. You can check the `getCurrentUser` function in `/api/src/lib/auth.ts` for that, or
2. You need to fetch the profile in both the `EditPostCell` and in `NewPost` and pass the `profile` prop to the `PostForm` component. You probably need to convert the `NewPost` component into a `NewPostCell` component for that to work.

I've just experimented with the last option and you can do it like this in the `EditPostCell`

Update the graphql query by including the profile using the `profileSelf` method (see the `profileSelf` method in `/api/src/services/profiles/profiles.ts`):
```ts
export const QUERY = gql`
  query EditPostById($id: Int!) {
    post: adminPost(id: $id) {
      id
      title
      body
      type
      createdAt
      published
      videoPost {
        videoUrl
      }
      coverImage {
        id
        imageId
        url
      }
    }
    profile: profileSelf {
      avatar
      name
    }
  }
`
```

Pass the new `profile` prop to the `PostForm`:

```tsx
export const Success = ({ post, profile }: CellSuccessProps<EditPostById>) => {
  
  // existing functions & logic and so on

  return (
    <div className="rw-segment">
      // ...header
      <div className="rw-segment-main">
        <PostForm
          post={post}
          profile={profile}
          onSave={onSave}
          error={error}
          loading={loading}
        />
      </div>
    </div>
  )
}
```

Then, in the `PostForm` component, you can pass it to the `Preview`

```tsx
// imports and other things

// include profile in props interface
interface PostFormProps {
  post?: EditPostById['post']
  profile: EditPostById['profile']
  onSave: (data: UpdatePostInput, id?: FormPost['id']) => void
  error: RWGqlError
  loading: boolean
}

// ...

const PostForm = (props: PostFormProps) => {

  // ...

  return (
    // ...
    <Preview
      // ...other props
      profile={profile}
    />
  )
}
````

**Review by Gakkenyak — COMMENTED** [review]
lbn

**Pull request merged**
