### PR TITLE
fix: Fix cover image issue

### PR DESCRIPTION
**Pull request by drikusroor**

### CODE REVIEW

**Comment by naomi-eliasar** [comment]
Not sure if it's related to this PR, but when I click the edit button of a video type post I get a 'something went wrong'

Scherm­afbeelding 2023-07-31 om 09 20 04

**Comment by naomi-eliasar** [comment]
When a post already exists and I go to change the image in edit mode, it seems like the new image is saved but the old image persists

**Comment by drikusroor** [comment]
> Not sure if it's related to this PR, but when I click the edit button of a video type post I get a 'something went wrong'.
> 
> If it's not related we can create a separate bug issue
> 
> Scherm­afbeelding 2023-07-31 om 09 20 04

I have probably fixed this in #90

**Comment by drikusroor** [comment]
> When a post already exists and I go to change the image in edit mode, it seems like the new image is saved but the old image persists

Could you check this again? I made some changes

**Comment by naomi-eliasar** [comment]
> > When a post already exists and I go to change the image in edit mode, it seems like the new image is saved but the old image persists
> 
> Could you check this again? I made some changes

It hasn't changed

**Comment by drikusroor** [comment]
> > > When a post already exists and I go to change the image in edit mode, it seems like the new image is saved but the old image persists
> > 
> > 
> > Could you check this again? I made some changes
> 
> It hasn't changed. The old image still remains I checked this in the deploy preview

Lol, some weird stuff is happening. See what happens if you do this:

- Update cover image of existing post
- Save it
- Update cover image of same post
- Save it
- Update cover image of same post
- Save it
- Now, go to edit form of same post. Don't edit it.
- Save it
- Repeat last two steps

If I do this, the cover image keeps changing even though I'm not updating the cover image...

**Comment by naomi-eliasar** [comment]
I can't access the deploy preview, I think the new database credentials have to be put in this branch?

**Pull request merged**
