### PR TITLE
Added: Add Image gallery backend

### PR DESCRIPTION
**Pull request by drikusroor**
This PR adds several models, sdls and services to the application with the following relations:

Every Post now has an array of ImageGalleryOnPost

Every ImageGalleryOnPost has an ImageGallery

Every ImageGallery has multiple images

I haven't yet created a frontend / form that will allow us to add new image galleries, but I have added an image gallery to a post in the seeder. My question to you @naomi-eliasar: Can you style the / an image gallery component that will display the images per gallery for a post? If you need more images, you can add some extra images / image galleries in [seed.ts](https://github.com/drikusroor/ohayo-goededagu/pull/107/files#diff-dc31c45b12f01153e351ab68c73d2d8b069b987d4595344f79b9af5e3116f924). 

In [ArticleArticle.tsx](https://github.com/drikusroor/ohayo-goededagu/pull/107/files#diff-a75258074168e9a399f45879318976bcf5c0c40ecf901a856e9ad250cf3b86ac) you can see how to get the image gallery from a post.

### CODE REVIEW

**Review by naomi-eliasar — CHANGES_REQUESTED** [review]
Can you add the folder, original_filename, public_id and tags properties of the image upload response to all image & image gallery models?

Or maybe it's easier to just add the entire cloudinary response as a 'file' property to the images?

Scherm­afbeelding 2023-09-04 om 10 53 44

**Comment by naomi-eliasar** [comment]
> > Can you add the `folder`, `original_filename`, `public_id` and `tags` properties of the image upload response to all image & image gallery models?
> > Or maybe it's easier to just add the entire cloudinary response as a 'file' property to the images?
> > Scherm­afbeelding 2023-09-04 om 10 53 44
> 
> Do we need those properties though? I think we should add them to the original Image model as well then

I thought it might be nice if we could rename the pictures and have that show as a description. It looks like cloudinary uses the `public_id` property for the name. But I'm not totally sure, could also be the `original_filename`, so I figured to add them both.

For the photo gallery I want to be able to check that they are all in the same folder, so I need the `folder` property for that.

I also figured if we manage to add a filter on post option (maybe not but let's see) it might also be nice to be able to filter on location, so if we add the `tags` property already to the Image we could do that relatively easily. (Adding tags to our articles for 'tokyo' or 'kyoto' and then filter on tags)

**Comment by naomi-eliasar** [comment]
> > > Can you add the `folder`, `original_filename`, `public_id` and `tags` properties of the image upload response to all image & image gallery models?
> > > Or maybe it's easier to just add the entire cloudinary response as a 'file' property to the images?
> > > Scherm­afbeelding 2023-09-04 om 10 53 44
> > 
> > 
> > Do we need those properties though? I think we should add them to the original Image model as well then
> 
> I thought it might be nice if we could rename the pictures and have that show as a description. It looks like cloudinary uses the `public_id` property for the name. But I'm not totally sure, could also be the `original_filename`, so I figured to add them both.
> 
> For the photo gallery I want to be able to check that they are all in the same folder, so I need the `folder` property for that.
> 
> I also figured if we manage to add a filter on post option (maybe not but let's see) it might also be nice to be able to filter on location, so if we add the `tags` property already to the Image we could do that relatively easily. (Adding tags to our articles for 'tokyo' or 'kyoto' and then filter on tags). But this one is big nth and most likely won't finsih this anyway. So, maybe not necessary yet

I found what they use for a title & description, it is not `public_id` or `original_filename`, but it is `context`
So public_id or original_filename do not need to be added, but `context` needs to be added

Scherm­afbeelding 2023-09-04 om 13 31 04

**Comment by drikusroor** [comment]
> > > > Can you add the `folder`, `original_filename`, `public_id` and `tags` properties of the image upload response to all image & image gallery models?
> > > > Or maybe it's easier to just add the entire cloudinary response as a 'file' property to the images?
> > > > Scherm­afbeelding 2023-09-04 om 10 53 44
> > > 
> > > 
> > > Do we need those properties though? I think we should add them to the original Image model as well then
> > 
> > 
> > I thought it might be nice if we could rename the pictures and have that show as a description. It looks like cloudinary uses the `public_id` property for the name. But I'm not totally sure, could also be the `original_filename`, so I figured to add them both.
> > For the photo gallery I want to be able to check that they are all in the same folder, so I need the `folder` property for that.
> > I also figured if we manage to add a filter on post option (maybe not but let's see) it might also be nice to be able to filter on location, so if we add the `tags` property already to the Image we could do that relatively easily. (Adding tags to our articles for 'tokyo' or 'kyoto' and then filter on tags). But this one is big nth and most likely won't finsih this anyway. So, maybe not necessary yet
> 
> I found what they use for a title & description it is `context`. When it has the key 'alt' it is the description and with the key 'caption' it is the title. To update this I also need the `public_id`. So public_id or original_filename do not need to be added, but `context` needs to be added
> 
> Scherm­afbeelding 2023-09-04 om 13 31 04
> 
> So recap on what to add to image:
> 
> * `context` & `public_id` to be able to add a title & description to an image
> * `folder` to be able to have all images from one photo gallery in the same cloudinary folder

Okay, I can add those things, but I will do it in a later PR because I don't want to make this one too big right now ;-)

**Review by naomi-eliasar — APPROVED** [review]

**Comment by naomi-eliasar** [comment]
> Okay, I can add those things, but I will do it in a later PR because I don't want to make this one too big right now ;-)

Very good, [new issue](https://github.com/users/drikusroor/projects/4/views/1?pane=issue&itemId=37630310)

**Pull request merged**
